/** @format */

export const GET_WORLD_NEWS_ATTEMP = 'GET_WORLD_NEWS_ATTEMP';
export const GET_WORLD_NEWS_SUCCESS = 'GET_WORLD_NEWS_SUCCESS';
export const GET_WORLD_NEWS_FAILURE = 'GET_WORLD_NEWS_FAILURE';

export const GET_SCIENCE_NEWS_ATTEMP = 'GET_SCIENCE_NEWS_ATTEMP';
export const GET_SCIENCE_NEWS_SUCCESS = 'GET_SCIENCE_NEWS_SUCCESS';
export const GET_SCIENCE_NEWS_FAILURE = 'GET_SCIENCE_NEWS_FAILURE';